# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CorridorDetection
                                 A QGIS plugin
 This plugin detects corridors on road network
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-09
        copyright            : (C) 2020 by Metehan Ergen / Hacettepe University - Politecnico di Milano
        email                : metehan.ergenn@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CorridorDetection class from file CorridorDetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .corridor_detection import CorridorDetection
    return CorridorDetection(iface)
